### ISSUE TITLE
Mapeamento e modelagem do cadastro das emoções

### ISSUE THREAD

**Issue by wssantanna** [Projeto-Emcoes-Next-Coders/MeuApp#3]

**Comment by EdneyCoutinho** [comment]
Primeiramente foi criado um diagrama de entidade relacionamento,
![Captura de Tela (12)](https://github.com/Projeto-Emcoes-Next-Coders/MeuApp/assets/159578376/a44a09a9-5f26-45cc-9e8a-59e881f3b7f9)
 para termos uma noção de como iria funcionar as relações entre as entidades iniciais da nossa aplicação.

**Comment by EdneyCoutinho** [comment]
Após revisarmos as necessidades da aplicação decidimos adicionar uma tabela de autenticação, para melhor funcionamento e maior segurança da aplicação, assim tirando os dados de email e senha da tabela usuário.
![Captura de Tela (13)](https://github.com/Projeto-Emcoes-Next-Coders/MeuApp/assets/159578376/7ea18a22-6553-4b57-9f3c-3834d76e1813)

**Comment by wssantanna** [comment]
### Ajuste no diagrama de entidades

### Revise a cardinalidade dos relacionamentos

- [ ] Revisa a cardinalidade dos relacionamentos, pois não estão retratando perfeitamente se a relação é `1:1`, `1:N` ou `N:N`. 

**Dica:** Um artigo bem legal para você revisar esse conteúdo é [este da Lucid](https://www.lucidchart.com/pages/pt/simbolos-de-diagramas-entidade-relacionamento#:~:text=data%20de%20publica%C3%A7%C3%A3o.-,Nota%C3%A7%C3%A3o%20de%20diagramas%20ER,-Enquanto%20a%20nota%C3%A7%C3%A3o).

**Comment by wssantanna** [comment]
### Publique o código fonte do DDL das Entidades

- [ ] Desenvolva e publique o código fonte do DDL das Entidades apresentadas no diagrama considerando o banco de dados PostgreSql.

**Comment by EdneyCoutinho** [comment]
Diagrama ER Atualizadado com novos nomes para entidades e outras pequenas atualizações.

![Captura de Tela (24)](https://github.com/Projeto-Emcoes-Next-Coders/MeuApp/assets/159578376/9e655df0-4be0-42e2-982f-2fc0e2a91efd)

**Comment by EdneyCoutinho** [comment]
Segue abaixo os comandos DDL inseridos para a criação das tabelas e seus respectivos relacionamentos.

create table usuario (
id integer primary key,
nome varchar (20) not null,
sobrenome varchar (100) not null,
naturalidade varchar(100) not null,
numero_telefone varchar(11) not null,
genero varchar(25),
data_nascimento date not null,
data_cadastro timestamp not null
);

create table credencial (
id integer primary key,
senha varchar (100) not null,
email varchar (100) not null,
id_usuario int unique, foreign key (id_usuario) references usuario(id)
);

create table reacao (
id integer primary key,
nome varchar (25) not null,
descricao text 
);

create table emocoes (
id integer primary key,
data_insercao timestamp not null,
motivo text,
usuario_id int,
reacao_id int,
foreign key (usuario_id) references usuario(id),
foreign key (reacao_id) references reacao(id)
);

**Comment by EdneyCoutinho** [comment]
Inserir novo usuário 
insert into usuario (id, nome, sobrenome, naturalidade, numero_telefone, genero, data_nascimento, data_cadastro)
values ();

Inserir a credencial do usuário
insert into credencial (id, senha, email, id_usuario)
values );

Inserir uma nova reação
insert into reacao (id, nome, descricao)
values ();

Inserir um novo registro de emoção
insert into emocoes (id, data_insercao, motivo, usuario_id, reacao_id)
values ();

**Comment by EdneyCoutinho** [comment]
Código fonte do DQL das entidades

Código fonte de consulta por credencial a partir de seu email e senha.
select *
from credencial
where email = 'junior@gmail.com' and senha = 'senha123';

Código fonte da consulta por um usuário a partir de sua id.
select *
from usuario
where id = 1;

 Código fonte de consulta de todas as reações cadastradas.
select * 
from reacao;

Código fonte da consulta por uma emoção a partir de sua id.
select *
from reacao
where id = 1;
 
Código fonte da consulta de todos os registros a partir de uma faixa de tempo (dia, semana, mês).
select*
from emocoes
where data_insercao >= '09/02/2024' and data_insercao < '08/03/2024';

Código fonte da consulta de um registro a partir de sua id.
select 
from emocoes
where id = 1;

Código fonte da consulta de um registro a partir do id de sua reação.
select*
from emocoes
where reacao_id = 1;
